= Gamepad


== Overview
This part of the documentation is the main focus of my interest.  As I've mentioned before, Valve implements the driver for this device inside the Steam client, which is proprietary.  Valve intentionally does not publish any documentation for this vitally important piece of the hardware, which is a huge "fuck you" to Linux, FOSS, privacy, consumer trust and openness in general.  Again, Valve is not a good Linux citizen.

The Steam Deck gamepad / controller uses a report structure similar to the Steam Controller, which makes a lot of sense.  In a way, the Steam Deck could be considered the Steam Controller 2, since it generally improves on the older design and adds more features.

== Hardware
....
Steam Deck Controller:
  Manufacturer:               Valve <1>
  Model:                      Steam Deck Controller
  Bus:                        Internal USB3
  Type:                       Human Interface Device
  Polling Rate:               250Hz <2>
  Driver:                     Proprietary userspace driver inside Steam client
  Input:
    Buttons:                  20 <3>
    Thumbsticks:              2
      Axes:                   X + Y
      Capacitive touch:       1 each
      Z-axis button:          1 each
    Triggers:                 2
      Axes:                   Z
    Trackpads:                2
      Axes:                   X, Y, Z (pressure)
      Capacitive touch:       Yes
  Haptics:                    L + R vibration.
....
<1> Probably not the OEM
<2> What I've observed so far.  Might be possible to set higher?
<3> 24 if you include trigger switches and trackpad press

'''

== Input Event Devices
....
/dev/input/event5:  Valve Software Steam Deck Controller <1>
/dev/input/event6:  Valve Software Steam Deck Controller <2>
....
<1> "Lizard Mode" keyboard device emulated through the gamepad hardware
<2> "Lizard Mode" mouse device emulated through the gamepad hardware

NOTE: Enumeration order is not guaranteed.

'''

== USB Interface
The gamepad USB interface looks like this:

.lsusb
....
Bus 003 Device 002: ID 28de:1205 Valve Software Steam Deck Controller
....

.lsusb -v -d28de:1205
[%collapsible%open]
====
....
Bus 003 Device 005: ID 28de:1205 Valve Software Steam Deck Controller
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x28de Valve Software
  idProduct          0x1205 
  bcdDevice            2.00
  iManufacturer           1 Valve Software
  iProduct                2 Steam Deck Controller
  iSerial                 3 MEDA228045B1
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0096
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0  <1>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      39
          Report Descriptor: (length is 39)
            Item(Global): Usage Page, data= [ 0x01 ] 1
                            Generic Desktop Controls
            Item(Local ): Usage, data= [ 0x06 ] 6
                            Keyboard
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Usage Page, data= [ 0x07 ] 7
                            Keyboard
            Item(Local ): Usage Minimum, data= [ 0xe0 ] 224
                            Control Left
            Item(Local ): Usage Maximum, data= [ 0xe7 ] 231
                            GUI Right
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x01 ] 1
            Item(Global): Report Count, data= [ 0x08 ] 8
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): Input, data= [ 0x01 ] 1
                            Constant Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage Minimum, data= [ 0x00 ] 0
                            No Event
            Item(Local ): Usage Maximum, data= [ 0x65 ] 101
                            Keyboard Application (Windows Key for Win95 or Compose)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x65 ] 101
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x06 ] 6
            Item(Main  ): Input, data= [ 0x00 ] 0
                            Data Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1  <2>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      50
          Report Descriptor: (length is 50)
            Item(Global): Usage Page, data= [ 0x01 ] 1
                            Generic Desktop Controls
            Item(Local ): Usage, data= [ 0x02 ] 2
                            Mouse
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Local ): Usage, data= [ 0x01 ] 1
                            Pointer
            Item(Main  ): Collection, data= [ 0x00 ] 0
                            Physical
            Item(Global): Usage Page, data= [ 0x09 ] 9
                            Buttons
            Item(Local ): Usage Minimum, data= [ 0x01 ] 1
                            Button 1 (Primary)
            Item(Local ): Usage Maximum, data= [ 0x03 ] 3
                            Button 3 (Tertiary)
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0x01 ] 1
            Item(Global): Report Size, data= [ 0x01 ] 1
            Item(Global): Report Count, data= [ 0x03 ] 3
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Report Size, data= [ 0x05 ] 5
            Item(Global): Report Count, data= [ 0x01 ] 1
            Item(Main  ): Input, data= [ 0x01 ] 1
                            Constant Array Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Global): Usage Page, data= [ 0x01 ] 1
                            Generic Desktop Controls
            Item(Local ): Usage, data= [ 0x30 ] 48
                            Direction-X
            Item(Local ): Usage, data= [ 0x31 ] 49
                            Direction-Y
            Item(Global): Logical Minimum, data= [ 0x81 ] 129
            Item(Global): Logical Maximum, data= [ 0x7f ] 127
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x02 ] 2
            Item(Main  ): Input, data= [ 0x06 ] 6
                            Data Variable Relative No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2  <3>
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      29
          Report Descriptor: (length is 29)
            Item(Global): Usage Page, data= [ 0xff 0xff ] 65535
                            (null)
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Collection, data= [ 0x01 ] 1
                            Application
            Item(Global): Logical Minimum, data= [ 0x00 ] 0
            Item(Global): Logical Maximum, data= [ 0xff 0x00 ] 255
            Item(Global): Report Size, data= [ 0x08 ] 8
            Item(Global): Report Count, data= [ 0x40 ] 64
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Input, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Output, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Local ): Usage, data= [ 0x01 ] 1
                            (null)
            Item(Main  ): Feature, data= [ 0x02 ] 2
                            Data Variable Absolute No_Wrap Linear
                            Preferred_State No_Null_Position Non_Volatile Bitfield
            Item(Main  ): End Collection, data=none
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Association:
      bLength                 8
      bDescriptorType        11
      bFirstInterface         3
      bInterfaceCount         2
      bFunctionClass          2 Communications
      bFunctionSubClass       2 Abstract (modem)
      bFunctionProtocol       1 AT-commands (v.25ter)
      iFunction               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface              0 
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x01
          call management
        bDataInterface          2
      CDC ACM:
        bmCapabilities       0x02
          line coding and serial state
      CDC Union:
        bMasterInterface        3
        bSlaveInterface         4 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval             255
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x05  EP 5 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
....
<1> "Lizard Mode" keyboard HID
<2> "Lizard Mode" mouse HID
<3> Gamepad / master HID
====

As the callouts indicate above, this USB device has 3 HID-class interfaces, each represents a kind of sub-device.  The first two are explained in more detail in the <<lizard_mode>> section below, but they are, in a sense, child devices of the third (`bInterfaceNum 2`) interface, which is the gamepad.

The gamepad interface sends input reports which contain (nearly) all the user-facing input states, including the trackpads which produce data for the "Lizard Mode" mouse interface uses.  The gamepad interface can also written to and is used to receive feature reports, whereas the the other two interfaces *cannot* receive feature reports.  The "Lizard Mode" mouse/keyboard interfaces can be *disabled*, but *only* by sending a feature report to the gamepad interface.  There is only one endpoint to receive reports.

Reading and writing this interface can be done in the usual ways, as with other USB and HID-class devices, so I wont go into how to use those APIs, but I do get into the HID reports, structures, etc which are are at the heart of OpenSD, in the <<hid_reports>> section.

'''

== Hidraw Interface
The gamepad is a HID-class USB device, so even without a driver, we can easily read and write to it through the kernel hidraw API.

(This is my dev system, so I have OpenSD udev rules installed.)
....
crw-rw---- 1 root opensd 241, 0 Nov 21 10:48 /dev/hidraw0
crw-rw---- 1 root opensd 241, 1 Nov 21 10:48 /dev/hidraw1
crw------- 1 root root   241, 2 Nov 21 10:48 /dev/hidraw2
crw-rw---- 1 root opensd 241, 3 Nov 21 10:48 /dev/hidraw3
....

In this case, `hidraw0`, `hidraw1` and `hidraw3` are all the same USB device for the "Steam Deck Controller", which is _most_ of the user-facing input features (buttons, sticks, triggers, pads, etc).  `hidraw2` is the touchscreen device, which I'll get into later.  How these devices are enumerated is not guaranteed, so you cannot rely on /dev/hidrawX always being your touchscreen or gamepad.  You need to determine which is what before attempting to read them.

'''

== Polling
Polling rate on this device seems(?) to be fixed to 250Hz, which is on the low end of USB polling, but it's debatable if more is really necessary.  It's also possible there's an issue with the kernel or udev which limits it.

'''

== Report Descriptors
[#keyboard_report_descriptor]
.Report Descriptor for interface 0 (Keyboard)
[%collapsible%open]
====
....
05 01 09 06 a1 01 05 07 19 e0 29 e7 15 00 25 01 75 01 95 08 81 02 81 01 19 00 29 65 15 00 25 65 75 08 95 06 81 00 c0 

  INPUT[INPUT]
    Field(0)
      Application(GenericDesktop.Keyboard)
      Usage(8)
        Keyboard.00e0
        Keyboard.00e1
        Keyboard.00e2
        Keyboard.00e3
        Keyboard.00e4
        Keyboard.00e5
        Keyboard.00e6
        Keyboard.00e7
      Logical Minimum(0)
      Logical Maximum(1)
      Report Size(1)
      Report Count(8)
      Report Offset(0)
      Flags( Variable Absolute )
    Field(1)
      Application(GenericDesktop.Keyboard)
      Usage(102)
        Keyboard.0000
        Keyboard.0001
        Keyboard.0002
        Keyboard.0003
        Keyboard.0004
        Keyboard.0005
        Keyboard.0006
        Keyboard.0007
        Keyboard.0008
        Keyboard.0009
        Keyboard.000a
        Keyboard.000b
        Keyboard.000c
        Keyboard.000d
        Keyboard.000e
        Keyboard.000f
        Keyboard.0010
        Keyboard.0011
        Keyboard.0012
        Keyboard.0013
        Keyboard.0014
        Keyboard.0015
        Keyboard.0016
        Keyboard.0017
        Keyboard.0018
        Keyboard.0019
        Keyboard.001a
        Keyboard.001b
        Keyboard.001c
        Keyboard.001d
        Keyboard.001e
        Keyboard.001f
        Keyboard.0020
        Keyboard.0021
        Keyboard.0022
        Keyboard.0023
        Keyboard.0024
        Keyboard.0025
        Keyboard.0026
        Keyboard.0027
        Keyboard.0028
        Keyboard.0029
        Keyboard.002a
        Keyboard.002b
        Keyboard.002c
        Keyboard.002d
        Keyboard.002e
        Keyboard.002f
        Keyboard.0030
        Keyboard.0031
        Keyboard.0032
        Keyboard.0033
        Keyboard.0034
        Keyboard.0035
        Keyboard.0036
        Keyboard.0037
        Keyboard.0038
        Keyboard.0039
        Keyboard.003a
        Keyboard.003b
        Keyboard.003c
        Keyboard.003d
        Keyboard.003e
        Keyboard.003f
        Keyboard.0040
        Keyboard.0041
        Keyboard.0042
        Keyboard.0043
        Keyboard.0044
        Keyboard.0045
        Keyboard.0046
        Keyboard.0047
        Keyboard.0048
        Keyboard.0049
        Keyboard.004a
        Keyboard.004b
        Keyboard.004c
        Keyboard.004d
        Keyboard.004e
        Keyboard.004f
        Keyboard.0050
        Keyboard.0051
        Keyboard.0052
        Keyboard.0053
        Keyboard.0054
        Keyboard.0055
        Keyboard.0056
        Keyboard.0057
        Keyboard.0058
        Keyboard.0059
        Keyboard.005a
        Keyboard.005b
        Keyboard.005c
        Keyboard.005d
        Keyboard.005e
        Keyboard.005f
        Keyboard.0060
        Keyboard.0061
        Keyboard.0062
        Keyboard.0063
        Keyboard.0064
        Keyboard.0065
      Logical Minimum(0)
      Logical Maximum(101)
      Report Size(8)
      Report Count(6)
      Report Offset(16)
      Flags( Array Absolute )

Keyboard.00e0 ---> Key.LeftControl
Keyboard.00e1 ---> Key.LeftShift
Keyboard.00e2 ---> Key.LeftAlt
Keyboard.00e3 ---> Key.LeftMeta
Keyboard.00e4 ---> Key.RightCtrl
Keyboard.00e5 ---> Key.RightShift
Keyboard.00e6 ---> Key.RightAlt
Keyboard.00e7 ---> Key.RightMeta
Keyboard.0000 ---> Sync.Report
Keyboard.0001 ---> Sync.Report
Keyboard.0002 ---> Sync.Report
Keyboard.0003 ---> Sync.Report
Keyboard.0004 ---> Key.A
Keyboard.0005 ---> Key.B
Keyboard.0006 ---> Key.C
Keyboard.0007 ---> Key.D
Keyboard.0008 ---> Key.E
Keyboard.0009 ---> Key.F
Keyboard.000a ---> Key.G
Keyboard.000b ---> Key.H
Keyboard.000c ---> Key.I
Keyboard.000d ---> Key.J
Keyboard.000e ---> Key.K
Keyboard.000f ---> Key.L
Keyboard.0010 ---> Key.M
Keyboard.0011 ---> Key.N
Keyboard.0012 ---> Key.O
Keyboard.0013 ---> Key.P
Keyboard.0014 ---> Key.Q
Keyboard.0015 ---> Key.R
Keyboard.0016 ---> Key.S
Keyboard.0017 ---> Key.T
Keyboard.0018 ---> Key.U
Keyboard.0019 ---> Key.V
Keyboard.001a ---> Key.W
Keyboard.001b ---> Key.X
Keyboard.001c ---> Key.Y
Keyboard.001d ---> Key.Z
Keyboard.001e ---> Key.1
Keyboard.001f ---> Key.2
Keyboard.0020 ---> Key.3
Keyboard.0021 ---> Key.4
Keyboard.0022 ---> Key.5
Keyboard.0023 ---> Key.6
Keyboard.0024 ---> Key.7
Keyboard.0025 ---> Key.8
Keyboard.0026 ---> Key.9
Keyboard.0027 ---> Key.0
Keyboard.0028 ---> Key.Enter
Keyboard.0029 ---> Key.Esc
Keyboard.002a ---> Key.Backspace
Keyboard.002b ---> Key.Tab
Keyboard.002c ---> Key.Space
Keyboard.002d ---> Key.Minus
Keyboard.002e ---> Key.Equal
Keyboard.002f ---> Key.LeftBrace
Keyboard.0030 ---> Key.RightBrace
Keyboard.0031 ---> Key.BackSlash
Keyboard.0032 ---> Key.BackSlash
Keyboard.0033 ---> Key.Semicolon
Keyboard.0034 ---> Key.Apostrophe
Keyboard.0035 ---> Key.Grave
Keyboard.0036 ---> Key.Comma
Keyboard.0037 ---> Key.Dot
Keyboard.0038 ---> Key.Slash
Keyboard.0039 ---> Key.CapsLock
Keyboard.003a ---> Key.F1
Keyboard.003b ---> Key.F2
Keyboard.003c ---> Key.F3
Keyboard.003d ---> Key.F4
Keyboard.003e ---> Key.F5
Keyboard.003f ---> Key.F6
Keyboard.0040 ---> Key.F7
Keyboard.0041 ---> Key.F8
Keyboard.0042 ---> Key.F9
Keyboard.0043 ---> Key.F10
Keyboard.0044 ---> Key.F11
Keyboard.0045 ---> Key.F12
Keyboard.0046 ---> Key.SysRq
Keyboard.0047 ---> Key.ScrollLock
Keyboard.0048 ---> Key.Pause
Keyboard.0049 ---> Key.Insert
Keyboard.004a ---> Key.Home
Keyboard.004b ---> Key.PageUp
Keyboard.004c ---> Key.Delete
Keyboard.004d ---> Key.End
Keyboard.004e ---> Key.PageDown
Keyboard.004f ---> Key.Right
Keyboard.0050 ---> Key.Left
Keyboard.0051 ---> Key.Down
Keyboard.0052 ---> Key.Up
Keyboard.0053 ---> Key.NumLock
Keyboard.0054 ---> Key.KPSlash
Keyboard.0055 ---> Key.KPAsterisk
Keyboard.0056 ---> Key.KPMinus
Keyboard.0057 ---> Key.KPPlus
Keyboard.0058 ---> Key.KPEnter
Keyboard.0059 ---> Key.KP1
Keyboard.005a ---> Key.KP2
Keyboard.005b ---> Key.KP3
Keyboard.005c ---> Key.KP4
Keyboard.005d ---> Key.KP5
Keyboard.005e ---> Key.KP6
Keyboard.005f ---> Key.KP7
Keyboard.0060 ---> Key.KP8
Keyboard.0061 ---> Key.KP9
Keyboard.0062 ---> Key.KP0
Keyboard.0063 ---> Key.KPDot
Keyboard.0064 ---> Key.102nd
Keyboard.0065 ---> Key.Compose
....
====

[#mouse_report_descriptor]
.Report Descriptor for interface 1 (mouse):
[%collapsible%open]
====
....
05 01 09 02 a1 01 09 01 a1 00 05 09 19 01 29 03 15 00 25 01 75 01 95 03 81 02 75 05 95 01 81 01 05 01 09 30 09 31 15 81 25 7f 75 08 95 02 81 06 c0 c0 

  INPUT[INPUT]
    Field(0)
      Physical(GenericDesktop.Pointer)
      Application(GenericDesktop.Mouse)
      Usage(3)
        Button.0001
        Button.0002
        Button.0003
      Logical Minimum(0)
      Logical Maximum(1)
      Report Size(1)
      Report Count(3)
      Report Offset(0)
      Flags( Variable Absolute )
    Field(1)
      Physical(GenericDesktop.Pointer)
      Application(GenericDesktop.Mouse)
      Usage(2)
        GenericDesktop.X
        GenericDesktop.Y
      Logical Minimum(-127)
      Logical Maximum(127)
      Report Size(8)
      Report Count(2)
      Report Offset(8)
      Flags( Variable Relative )

Button.0001 ---> Key.LeftBtn
Button.0002 ---> Key.RightBtn
Button.0003 ---> Key.MiddleBtn
GenericDesktop.X ---> Relative.X
GenericDesktop.Y ---> Relative.Y
....
====

[#gamepad_report_descriptor]
.Report Descriptor for interface 2 (gamepad):
[%collapsible%open]
====
....
06 ff ff 09 01 a1 01 15 00 26 ff 00 75 08 95 40 09 01 81 02 09 01 91 02 09 01 b1 02 c0 

  INPUT[INPUT]
    Field(0)
      Application(Vendor-specific-FF.0001)
      Usage(64)
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
      Logical Minimum(0)
      Logical Maximum(255)
      Report Size(8)
      Report Count(64)
      Report Offset(0)
      Flags( Variable Absolute )
  OUTPUT[OUTPUT]
    Field(0)
      Application(Vendor-specific-FF.0001)
      Usage(64)
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
      Logical Minimum(0)
      Logical Maximum(255)
      Report Size(8)
      Report Count(64)
      Report Offset(0)
      Flags( Variable Absolute )
  FEATURE[FEATURE]
    Field(0)
      Application(Vendor-specific-FF.0001)
      Usage(64)
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
        Vendor-specific-FF.0001
      Logical Minimum(0)
      Logical Maximum(255)
      Report Size(8)
      Report Count(64)
      Report Offset(0)
      Flags( Variable Absolute )

Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
Vendor-specific-FF.0001 ---> Sync.Report
....
====

Notably, there is no mention of report ID's in the descriptors, so from that we know that the device does *not* use numbered reports, so all use of report IDs should be zero where applicible.  We can also see that the input, output and feature reports all use a 64-byte structure.

It's not really necessary to get into the USB protocol, so we'll just focus on the HID data payload of the report.  If you're working with a hidraw interface you only need to deal with report numbers, if at all.  Since the Steam Deck Controller does not use numbered reports, all we need to worry about is the raw report payload.

'''

== Input Reports
The Steam Deck Controller sends regular reports over the normal interrupt endpoint, so you don't need to request them.  At least I haven't found a reason to yet.

Again, this is all guesswork since Valve has not published anything definitive for the Steam Deck _or the Steam Controller, which came out 7 years ago_.  Due to the similarities with the Steam Controller, this it is my *guess* that input reports follow a similar pattern, which is also a guess, lol.

My current theory is that the first two bytes indicate the version of the protocol/firmware/report structure/whatever as major-minor values, the third byte indicates the type of data for the report, the fourth byte is the payload size, and after that follows the actual payload data.  Since all reports are 64 bytes in size, the payload can be up to 60 bytes.

In my experimentation, I've only received one type of input report from the interrupt, whereas the Steam Controller is known to send battery levels and wireless connection status.  So... it's hard to prove the meanings here, but the theory can be demonstrated to work at least.  If there are other types of input reports, I suspect the third byte will reflect that.

....
┌───────────────┬──────┬──────────┬──────────┬───────────────────────────────────────────────────────────────────┐
│     Name      │ Bits │   Type   │ Byte Num │                            Description                            │
├───────────────┼──────┼──────────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ major_ver     │    8 │ uint8_t  │      0   │ Major version?  Always 0x01 (same as SC)                          │
│ minor_ver     │    8 │ uint8_t  │      1   │ Minor version?  Always 0x00 (same as SC)                          │
│ report_type   │    8 │ uint8_t  │      2   │ Input report type?                                                │
│ report_size   │    8 │ uint8_t  │      3   │ Total size of report, in bytes.                                   │
│ payload_data  │    - │    -     │   4-63   │ Payload data.  Up to 60 bytes.                                    │
└───────────────┴──────┴──────────┴──────────┴───────────────────────────────────────────────────────────────────┘
....

'''

=== Input Data Report
This report contains all the state-data for every sensor in the gamepad portion of the Steam Deck.  The volume buttons, power button and touchscreen are separate devices.

The report size is 64 bytes long and can be read as a tightly packed struct in this order.  This is a slightly reformatted copy of the code that OpenSD uses.
....
┌───────────────┬──────┬──────────┬──────────┬───────────────────────────────────────────────────────────────────┐
│     Name      │ Bits │   Type   │ Byte Num │                            Description                            │
├───────────────┼──────┼──────────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ major_ver     │    8 │ uint8_t  │      0   │ Major version?  Always 0x01 (same as SC)                          │
│ minor_ver     │    8 │ uint8_t  │      1   │ Minor version?  Always 0x00 (same as SC)                          │
│ report_type   │    8 │ uint8_t  │      2   │ Input report type? Always 0x09, which I'm assuming means gamepad? │
│ report_size   │    8 │ uint8_t  │      3   │ Actual size of total report, in bytes. Always 0x40 (64 bytes)     │
│ frame         │   32 │ uint32_t │      4   │ Input frame counter?                                              │
│ r2            │    1 │ bool     │      8.0 │ Binary sensor for analogue triggers                               │
│ l2            │    1 │ bool     │      8.1 │ “                                                                 │
│ r1            │    1 │ bool     │      8.2 │ Shoulder buttons                                                  │
│ l1            │    1 │ bool     │      8.3 │ “                                                                 │
│ y             │    1 │ bool     │      8.4 │ Button cluster                                                    │
│ b             │    1 │ bool     │      8.5 │ “                                                                 │
│ x             │    1 │ bool     │      8.6 │ “                                                                 │
│ a             │    1 │ bool     │      8.7 │ “                                                                 │
│ up            │    1 │ bool     │      9.0 │ Directional Pad buttons                                           │
│ right         │    1 │ bool     │      9.1 │ “                                                                 │
│ left          │    1 │ bool     │      9.2 │ “                                                                 │
│ down          │    1 │ bool     │      9.3 │ “                                                                 │
│ options       │    1 │ bool     │      9.4 │ View / Overlapping square ⧉  button located above left stick      │
│ steam         │    1 │ bool     │      9.5 │ STEAM button below left trackpad                                  │
│ menu          │    1 │ bool     │      9.6 │ Hamburger (☰) button located above right stick                    │
│ l5            │    1 │ bool     │      9.7 │ L5 & R5 on the back of the deck                                   │
│ r5            │    1 │ bool     │     10.0 │ “                                                                 │
│ l_pad_press   │    1 │ bool     │     10.1 │ Binary press sensor for trackpads                                 │
│ r_pad_press   │    1 │ bool     │     10.2 │ “                                                                 │
│ l_pad_touch   │    1 │ bool     │     10.3 │ Binary touch sensor for trackpads                                 │
│ r_pad_touch   │    1 │ bool     │     10.4 │ “                                                                 │
│ _unk3         │    1 │ bool     │     10.5 │ Unknown                                                           │
│ l3            │    1 │ bool     │     10.6 │ Z-axis button on the left stick                                   │
│ _unk4         │    1 │ bool     │     10.7 │ Unknown                                                           │
│ _unk5         │    1 │ bool     │     11.0 │ “                                                                 │
│ _unk6         │    1 │ bool     │     11.1 │ “                                                                 │
│ r3            │    1 │ bool     │     11.2 │ Z-axis button on the right stick                                  │
│ _unk7         │    1 │ bool     │     11.3 │ Unknown                                                           │
│ _unk8         │    1 │ bool     │     11.4 │ “                                                                 │
│ _unk9         │    1 │ bool     │     11.5 │ “                                                                 │
│ _unk10        │    1 │ bool     │     11.6 │ “                                                                 │
│ _unk11        │    1 │ bool     │     11.7 │ “                                                                 │
│ _unk12        │    1 │ bool     │     12.0 │ No readings on any of these.                                      │
│ _unk13        │    1 │ bool     │     12.1 │ “                                                                 │
│ _unk14        │    1 │ bool     │     12.2 │ “                                                                 │
│ _unk15        │    1 │ bool     │     12.3 │ “                                                                 │
│ _unk16        │    1 │ bool     │     12.4 │ “                                                                 │
│ _unk17        │    1 │ bool     │     12.5 │ “                                                                 │
│ _unk18        │    1 │ bool     │     12.6 │ “                                                                 │
│ _unk19        │    1 │ bool     │     12.7 │ “                                                                 │
│ _unk20        │    1 │ bool     │     13.0 │ “                                                                 │
│ l4            │    1 │ bool     │     13.1 │ L4 & R4 on the back of the deck                                   │
│ r4            │    1 │ bool     │     13.2 │ “                                                                 │
│ _unk21        │    1 │ bool     │     13.3 │ Unknown                                                           │
│ _unk22        │    1 │ bool     │     13.4 │ “                                                                 │
│ _unk23        │    1 │ bool     │     13.5 │ “                                                                 │
│ l_stick_touch │    1 │ bool     │     13.6 │ Binary touch sensors on the stick controls                        │
│ r_stick_touch │    1 │ bool     │     13.7 │ “                                                                 │
│ _unk24        │    1 │ bool     │     14.0 │ Unknown                                                           │
│ _unk25        │    1 │ bool     │     14.1 │ “                                                                 │
│ quick_access  │    1 │ bool     │     14.2 │ Quick Access (...) button below right trackpad                    │
│ _unk26        │    1 │ bool     │     14.3 │ Unknown                                                           │
│ _unk27        │    1 │ bool     │     14.4 │ “                                                                 │
│ _unk28        │    1 │ bool     │     14.5 │ “                                                                 │
│ _unk29        │    1 │ bool     │     14.6 │ “                                                                 │
│ _unk30        │    1 │ bool     │     14.7 │ “                                                                 │
│ _unk31        │    8 │ uint8_t  │     15   │ Not sure, maybe padding or just unused                            │
│ l_pad_x       │   16 │ int16_t  │     16   │ Trackpad touch coordinates                                        │
│ l_pad_y       │   16 │ int16_t  │     18   │ “                                                                 │
│ r_pad_x       │   16 │ int16_t  │     20   │ “                                                                 │
│ r_pad_y       │   16 │ int16_t  │     22   │ “                                                                 │
│ accel_x       │   16 │ int16_t  │     24   │ Accelerometers I think.  Needs more testing.                      │
│ accel_y       │   16 │ int16_t  │     26   │ “                                                                 │
│ accel_z       │   16 │ int16_t  │     28   │ “                                                                 │
│ pitch         │   16 │ int16_t  │     30   │ Attitude (?)  Needs more testing.                                 │
│ yaw           │   16 │ int16_t  │     32   │ “                                                                 │
│ roll          │   16 │ int16_t  │     34   │ “                                                                 │
│ _gyro0        │   16 │ int16_t  │     36   │ Not sure what these are...                                        │
│ _gyro1        │   16 │ int16_t  │     38   │ Seems like they might be additional gyros for extra precision (?) │
│ _gyro2        │   16 │ int16_t  │     40   │ “                                                                 │
│ _gyro3        │   16 │ int16_t  │     42   │ “                                                                 │
│ l_trigg       │   16 │ uint16_t │     44   │ Pressure sensors for L2 & R2 triggers                             │
│ r_trigg       │   16 │ uint16_t │     46   │ “                                                                 │
│ l_stick_x     │   16 │ int16_t  │     48   │ Analogue thumbsticks                                              │
│ l_stick_y     │   16 │ int16_t  │     50   │ “                                                                 │
│ r_stick_x     │   16 │ int16_t  │     52   │ “                                                                 │
│ r_stick_y     │   16 │ int16_t  │     54   │ “                                                                 │
│ l_pad_force   │   16 │ uint16_t │     56   │ Touchpad pressure sensors                                         │
│ r_pad_force   │   16 │ uint16_t │     58   │ “                                                                 │
│ l_stick_force │   16 │ uint16_t │     60   │ Thumbstick capacitive sensors                                     │
│ r_stick_force │   16 │ uint16_t │     62   │ “                                                                 │
└───────────────┴──────┴──────────┴──────────┴───────────────────────────────────────────────────────────────────┘
....

'''

[#feature_reports]
== Feature Reports
Although numbered reports are not used, there are different types.  The report type is specified as the first byte in the HID data payload.  I've found most of the reports are the same as the SC, so I've used the SC kernel driver for a bit of reference to their names.

Output and Feature reports are 64 bytes, but may have shorter payloads.  Reports with shorter payloads should be padded with zeroes.

.Feature Reports
----
SET_MAPPINGS                = 0x80
CLEAR_MAPPINGS              = 0x81
GET_MAPPINGS                = 0x82
GET_ATTRIB                  = 0x83
GET_ATTRIB_LABEL            = 0x84
DEFAULT_MAPPINGS            = 0x85
FACTORY_RESET               = 0x86
WRITE_REGISTER              = 0x87
CLEAR_REGISTER              = 0x88
READ_REGISTER               = 0x89
GET_REGISTER_LABEL          = 0x8a
GET_REGISTER_MAX            = 0x8b
GET_REGISTER_DEFAULT        = 0x8c
SET_MODE                    = 0x8d
DEFAULT_MOUSE               = 0x8e
FORCE_FEEDBACK              = 0x8f
REQUEST_COMM_STATUS         = 0xb4
GET_SERIAL                  = 0xae
HAPTIC_PULSE (?)            = 0xea
----

'''

=== Registers
The Steam Deck Controller has programmable registers, which can be set, read and cleared feature reports.  The report types are `WRITE_REGISTER`, `READ_REGISTER` and `CLEAR_REGISTER` as listed in the <<feature_reports>> section.

.Known Registers
----
LPAD_MODE                   = 0x07
RPAD_MODE                   = 0x08
RPAD_MARGIN                 = 0x18
GYRO_MODE                   = 0x30
----

There are certainly more, but its difficult to sniff them out and figure out what they do.

'''
==== Reading Registers

TODO

'''

==== Writing Registers

....
┌───────────────┬──────┬──────────┬───────────────────────────────────────────────────────────────────┐
│     Name      │ Bits │ Byte Num │                            Description                            │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ report_type   │    8 │     0    │ WRITE_REGISTER (0x87)                                             │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ payload_size  │    8 │     1    │ Size of register / value pairs, in bytes (3 for single register)  │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ register      │    8 │     2    │ One of the registers from the list above                          │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ value (lo-hi) │   16 │     3    │ Register values are 16 bits, with the low 8 bits first            │
└───────────────┴──────┴──────────┴───────────────────────────────────────────────────────────────────┘
....

Multiple registers can be written at once, with the format extending the register/value pairs.  The payload size needs to reflect size of all register/value pairs (3 bytes each) in the report.  This way payload_size should be 3 times the number of registers being written.

'''

==== Clearing Registers:

....
┌───────────────┬──────┬──────────┬───────────────────────────────────────────────────────────────────┐
│     Name      │ Bits │ Byte Num │                            Description                            │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ report_type   │    8 │     0    │ CLEAR_REGISTER (0x88)                                             │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ payload_size  │    8 │     1    │ Size of register list, in bytes (1 for single register)           │
├───────────────┼──────┼──────────┼───────────────────────────────────────────────────────────────────┤
│ register      │    8 │     2    │ One of the registers from the list above                          │
└───────────────┴──────┴──────────┴───────────────────────────────────────────────────────────────────┘
....

Multiple registers can be cleared at once, same as with writing them, although payload_size will only be a multiple of 1.

'''

=== Haptic / FF Reports

TODO

'''
